version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      pip-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    directory: '/ui'
    schedule:
      interval: 'monthly'
    groups:
      npm-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'typescript'
